apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: study-app
spec:
  selector:
    component: backend
  ports:
    - name: http
      port: 22112
      targetPort: 22112
  type: LoadBalancer

